// src/react/OtTabs.jsx
/**
 * oat - React Tabs Component
 * Renders the ot-tabs web component structure.
 * Derived from the ot-tabs custom element (src/js/tabs.js).
 *
 * Usage:
 *   <OtTabs tabs={['Account', 'Password']} onChange={i => console.log(i)}>
 *     <div>Account content</div>
 *     <div>Password content</div>
 *   </OtTabs>
 */

import { Children, useRef, useCallback } from 'react';
import { useOtEvent } from './base.js';

export function OtTabs({ tabs = [], defaultIndex = 0, onChange, className, children }) {
  const ref = useRef(null);

  const handleChange = useCallback(
    (e) => onChange && onChange(e.detail.index, e.detail.tab),
    [onChange]
  );

  useOtEvent(ref, 'ot-tab-change', onChange ? handleChange : null);

  const panels = Children.toArray(children);

  return (
    <ot-tabs ref={ref} class={className}>
      <div role="tablist">
        {tabs.map((label, i) => (
          <button key={i} role="tab" aria-selected={i === defaultIndex ? 'true' : 'false'}>
            {label}
          </button>
        ))}
      </div>
      {panels.map((panel, i) => (
        <div key={i} role="tabpanel">{panel}</div>
      ))}
    </ot-tabs>
  );
}

// src/vue/OtTabs.vue
<!--
  oat - Vue Tabs Component
  Renders the ot-tabs web component structure.
  Derived from the ot-tabs custom element (src/js/tabs.js).

  Usage:
    <OtTabs :tabs="['Account', 'Password']" v-model="activeTab">
      <template #tab-0>Account content</template>
      <template #tab-1>Password content</template>
    </OtTabs>
-->

<template>
  <ot-tabs ref="el" @ot-tab-change="onTabChange">
    <div role="tablist">
      <button
        v-for="(tab, i) in tabs"
        :key="i"
        role="tab"
        :aria-selected="String(i === modelValue)"
      >{{ tab }}</button>
    </div>
    <div v-for="(_, i) in tabs" :key="i" role="tabpanel">
      <slot :name="`tab-${i}`" />
    </div>
  </ot-tabs>
</template>

<script setup>
const props = defineProps({
  tabs: { type: Array, default: () => [] },
  modelValue: { type: Number, default: 0 }
});

const emit = defineEmits(['update:modelValue', 'change']);

function onTabChange(e) {
  emit('update:modelValue', e.detail.index);
  emit('change', e.detail.index, e.detail.tab);
}
</script>
